version: "3"

services:
        app:
                build:
                        context: .
                ports:
                  -  "8080:8080"
                volumes:
                        - ./var/jenkins_home
                command: sh -c "jenkins-job test ~/jobs/job1.yaml && jenkins-job update jobs"

